version: "3"

services:
  avatar:
    container_name: avatar.admin.sandbox
    image: 5824600/avatar-admin
    network_mode: host
    volumes:
      - .:/root/avatar/src
      - ${HOME}/avatar/qrcodes:/root/avatar/qrcodes
      - ${HOME}/avatar/ssh:/root/avatar/ssh
    environment:
      - MYSQL_USER=avatar
      - APPCONFIG=resources/config.app.sandbox.yml
