version: "3"

services:
  avatar:
    container_name: avatar.sandbox
    image: 5824600/avatar
    networks:
      - avatar.network
    volumes:
      - .:/root/avatar/src
      - ${HOME}/avatar/static:/root/avatar/static
      - ${HOME}/avatar/ssh:/root/avatar/ssh
      - ${HOME}/avatar/logs:/root/avatar/logs
    environment:
      - MYSQL_USER=avatar
      - APPCONFIG=resources/config.app.sandbox.yml
      - LOGCONFIG=resources/config.log.sandbox.yml

networks:
  avatar.network:
    external: true