version: "3"

services:
  avatar:
    container_name: avatar.admin.sandbox
    image: 5824600/avatar-admin
    network_mode: host
    volumes:
      - .:/root/avatar/src
      - ${HOME}/avatar/qrcodes:/root/avatar/qrcodes
      - ${HOME}/avatar/ssl:/root/avatar/ssl
      - ${HOME}/avatar/config:/root/avatar/config
    environment:
      - MYSQL_USER=avatar
      - APPCONFIG=/root/avatar/config/app.sandbox.yml
