version: "3"

services:
  avatar:
    container_name: avatar.sandbox
    image: 5824600/avatar
    network_mode: host
    volumes:
      - .:/root/avatar/src
      - ${HOME}/avatar/static:/root/avatar/static
      - ${HOME}/avatar/ssh:/root/avatar/ssh
    environment:
      - MYSQL_USER=avatar
      - APPCONFIG=resources/config.app.sandbox.yml
