version: "3"

services:
  avatar:
    container_name: avatar.sandbox.server
    image: 5824600/avatar-server
    network_mode: host
    volumes:
      - .:/avatar
    environment:
      - MYSQL_USER=avatar
