ENV: development
DEBUG: True

runwith:
  host: 0.0.0.0
  port: 5000

mysql:
  host: localhost
  port: 3306
  user: avatar
  password: !!os/env MYSQL_USER_PASSWORD
  database: avatar

redis:
  host: localhost
  port: 6379
  max_connections: 32