ENV: development
DEBUG: True

server:
  protocal: http
  domain: localhost
  port: 80
  apikey: ''

runwith:
  host: 0.0.0.0
  port: 5000

deployversion: 1

corp:
  name: '柳州宽带报装服务中心'
  logo: https://p.qpic.cn/pic_wework/2137366422/6563ce69edfc9b37949c019b4566430182da3ad6b2147beb/0
  inviteurl: https://work.weixin.qq.com/join_form/AMtldH4SxKalVAYbKpS6kA/hb_share_mng_mjoin
  qrcodes:
    joinus: https://work.weixin.qq.com/wework_admin/genqrcode?action=join&vcode=00cb65747e12c4a6a554061b2a94ba90&r=hb_share_mng_mjoin
    workbench: https://p.qpic.cn/pic_wework/4281450869/9e9824923ad5f42b7bb38ab638868939391d0f20b8a43483/0

wechat:
  corpid: ww165e7ece64ebbd81
  tokenurl: https://qyapi.weixin.qq.com/cgi-bin/gettoken
  loginurl: https://open.weixin.qq.com/connect/oauth2/authorize
  userinfourl: https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo
  userdetail: https://qyapi.weixin.qq.com/cgi-bin/user/get
  notifyurl: https://qyapi.weixin.qq.com/cgi-bin/message/send

apps:
  backend:
    agentId: 1000002
    secret: mbaBxnfl1HYnN-Gl-lRyeHGcVYx-IkgJgw9zrnySPYY
  addressbook:
    deptid: 1
    secret: MtLWmZnP2fFVoLGqW3Wp-_I49ZXTytgB37nSj8Pzd5g
    apiurl: https://qyapi.weixin.qq.com/cgi-bin/user/list
  order:
    agentid: 1000003
    secret: Qyb8Tz_8gYeSbmz6dp6XpGBONdTDEra3C1LLBkoUKz8


minprogram:
  appid: wxc6e44203b5cf3eb3
  secret: 1f2c8578d3be08ca9bb06a09f2ff1c70
  tokenurl: https://api.weixin.qq.com/cgi-bin/token
  homepage: pages/index/index
  qrcode:
    createurl: https://api.weixin.qq.com/wxa/getwxacodeunlimit
    storage: !!os/expandvars ${HOME}/avatar/qrcodes

mysql:
  host: localhost
  port: 3306
  user: avatar
  password: !!os/env MYSQL_USER_PASSWORD
  database: avatar

redis:
  host: localhost
  port: 6379
  max_connections: 32