ENV: development
DEBUG: True

runwith:
  host: 0.0.0.0
  port: 5000

deployversion: 1

corp:
  id: ww7a9620bfb16c987e
  name: '柳州宽带报装'
  logo: https://p.qpic.cn/pic_wework/2137366422/6563ce69edfc9b37949c019b4566430182da3ad6b2147beb/0
  inviteurl: https://work.weixin.qq.com/join_form/bfovcBtsE9O1eTvODTotYg/hb_share_mng_mjoin
  qrcodes:
    joinus: https://work.weixin.qq.com/wework_admin/genqrcode?action=join&vcode=6dfa2f701b6c13d3b5793bce0d3a2d62&r=pc_qrcode_hb_share_mng_mjoin
    workbench: https://p.qpic.cn/pic_wework/2137366422/4046eb4c3dafd25232843d05673a4c4900c0ef27c2d007a4/0

mysql:
  host: localhost
  port: 3306
  user: avatar
  password: !!os/env MYSQL_USER_PASSWORD
  database: avatar

redis:
  host: localhost
  port: 6379
  max_connections: 32