version: 1
handlers:
  public:
    level: INFO
    class: logging.handlers.TimedRotatingFileHandler
    filename: !!os/expandvars ${HOME}/avatar/logs/public
    formatter: simple
    when: D
  root:
    level: INFO
    class: logging.handlers.TimedRotatingFileHandler
    filename: !!os/expandvars ${HOME}/avatar/logs/root
    formatter: simple
    when: D
  gunicorn:
    level: INFO
    class: logging.handlers.TimedRotatingFileHandler
    filename: !!os/expandvars ${HOME}/avatar/logs/gunicorn
    formatter: simple
    when: D
  gunicorn.access:
    level: INFO
    class: logging.handlers.TimedRotatingFileHandler
    filename: !!os/expandvars ${HOME}/avatar/logs/access
    formatter: simple
    when: D
loggers:
  public:
    level: INFO
    handlers: [public]
    propagate: False
  gunicorn.error:
    level: INFO
    handlers: [gunicorn]
    propagate: False
  gunicorn.access:
    level: INFO
    handlers: [gunicorn.access]
    propagate: False
root:
  handlers: [root]

