ENV: development
DEBUG: True
SECRET_KEY: lzkdbz
SEND_FILE_MAX_AGE_DEFAULT: 10

server:
  protocal: http
  domain: www.lzkdbz.com:5000
  apikey: ''

runwith:
  host: 0.0.0.0
  port: 5000

deployversion: 20181019051212

corp:
  name: '柳州宽带报装服务中心'
  icp: '桂ICP备18009184号-1'
  logo: https://p.qpic.cn/pic_wework/2137366422/6563ce69edfc9b37949c019b4566430182da3ad6b2147beb/0
  inviteurl: https://work.weixin.qq.com/join_form/AMtldH4SxKalVAYbKpS6kA/hb_share_mng_mjoin
  workbench: https://p.qpic.cn/pic_wework/4281450869/9e9824923ad5f42b7bb38ab638868939391d0f20b8a43483/0
  manager:
    name: 张斌财
    mobile: 18977241191


wechat:
  corpid: ww165e7ece64ebbd81
  tokenurl: https://qyapi.weixin.qq.com/cgi-bin/gettoken
  userinfourl: https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo
  userdetail: https://qyapi.weixin.qq.com/cgi-bin/user/get
  notifyurl: https://qyapi.weixin.qq.com/cgi-bin/message/send
  loginurl: https://open.weixin.qq.com/connect/oauth2/authorize
  tagurl: https://qyapi.weixin.qq.com/cgi-bin/tag/get
  blueprintname: wechat
  loginredirect: /login

apps:
  backend:
    agentId: 1000002
    secret: mbaBxnfl1HYnN-Gl-lRyeHGcVYx-IkgJgw9zrnySPYY
  addressbook:
    deptid: 1
    secret: MtLWmZnP2fFVoLGqW3Wp-_I49ZXTytgB37nSj8Pzd5g
    apiurl: https://qyapi.weixin.qq.com/cgi-bin/user/list
  order:
    agentid: 1000003
    secret: Qyb8Tz_8gYeSbmz6dp6XpGBONdTDEra3C1LLBkoUKz8


minprogram:
  appid: wxc6e44203b5cf3eb3
  secret: 1f2c8578d3be08ca9bb06a09f2ff1c70
  tokenurl: https://api.weixin.qq.com/cgi-bin/token
  homepage: pages/start/index
  qrcode:
    createurl: https://api.weixin.qq.com/cgi-bin/wxaapp/createwxaqrcode

public:
  staticfolderurl: /public/static
  staticfolder: !!os/expandvars ${HOME}/avatar/static/

mysql:
  host: localhost
  port: 3306
  user: avatar
  password: !!os/env MYSQL_USER_PASSWORD
  database: avatar

redis:
  host: localhost
  port: 6379
  max_connections: 32